<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Chat.aspx.cs" Inherits="Chat" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Chat</title>
    <link type="text/css" rel="stylesheet" href="themes/css/ChatStyle.css" />
    <link type="text/css" rel="stylesheet" href="Themes/css/bubbleChat.css" />
    <link type="text/css" rel="stylesheet" href="materialize/css/materialize.css" />
   <%-- <link type="text/css" rel="stylesheet" href="materialize/font" />--%>
    <link rel="stylesheet" href="themes/Css/JQueryUI/themes/base/jquery.ui.all.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-2.2.0.min.js"></script>

    <script src="Scripts/jquery.ui.core.js"></script>
    <script src="Scripts/jquery.ui.widget.js"></script>
    <script src="Scripts/jquery.ui.mouse.js"></script>
    <script src="Scripts/jquery.ui.draggable.js"></script>
    <script src="Scripts/jquery.ui.resizable.js"></script>
    <script src="materialize/js/materialize.min.js"></script>
  <%--  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>--%>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-1.0.1.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    
    <script type="text/javascript">
        
        var audioElement = document.createElement('audio');
        audioElement.setAttribute('src', 'audio/chat.mp3');
        $(function () {

            $("#resizable").resizable();

        });

        

        $(function () {

            setScreen(false);

            // Declare a proxy to reference the hub. 
            var chatHub = $.connection.chatHub;
          
            registerClientMethods(chatHub);

            // Start Hub
            $.connection.hub.start().done(function () {

                registerEvents(chatHub)

            });

        });

        function setScreen(isLogin) {

            if (!isLogin) {

                $("#divChat").hide();
                $("#divLogin").show();
            }
            else {

                $("#divChat").show();
                $("#divLogin").hide();
            }

        }
        function getUser(id) {
            $.ajax({
                type: "Post",
                contentType: "application/json; charset=utf-8",
                url: "Chat.aspx/ObtenerUsuario",
                data: '{usu: ' + id + '}',
                dataType: 'json',
                success: function (data) {
                    var user = $.parseJSON(data.d);
                    $("#txtNickName").val(user);
                    
                },
                error: function () {
                    alert("Ocurrio algún error ");
                }
            });
        }
        
        function getCarrera(id) {
            $.ajax({
                type: "Post",
                contentType: "application/json; charset=utf-8",
                url: "Chat.aspx/ObtenerCarrera",
                data: '{id: ' + id + '}',
                dataType: 'json',
                success: function (data) {
                    var carrera = $.parseJSON(data.d);
                    $("#nameCarrera").text(carrera);
                    console.log(carrera);

                },
                error: function () {
                    alert("Ocurrio algún error ");
                }
            });
        }

        function registerEvents(chatHub) {
            getUser(<%=Server.HtmlEncode(Session["IdUsuario"].ToString())%>);
           
            $("#btnStartChat").click(function () {
               
                var name = $("#txtNickName").val();
                var filtro = $("#txtNickName").val();
                var filtro = filtro.split(' ');
                var carrera = filtro[0];
                getCarrera(carrera);
                
                if (name.length > 0) {
                    chatHub.server.connect(name);
                    
                }

            });


            $('#btnSendMsg').click(function () {
                var filtro = $("#txtNickName").val();
                var filtro = filtro.split(' ');
                var msg = $("#txtMessage").val();
                if (msg.length > 0) {

                    var userName = $('#hdUserName').val();
                    chatHub.server.sendMessageToAll(userName, msg, filtro[0]);
                    $("#txtMessage").val('');
                }
            });


            $("#txtNickName").keypress(function (e) {
                if (e.which == 13) {
                    $("#btnStartChat").click();
                }
            });

            $("#txtMessage").keypress(function (e) {
                if (e.which == 13) {
                    $('#btnSendMsg').click();
                }
            });

        }

        function registerClientMethods(chatHub) {

            // Calls when user successfully logged in
            chatHub.client.onConnected = function (id, userName, allUsers, messages) {

                setScreen(true);

                $('#hdId').val(id);
                $('#hdUserName').val(userName);
                $('#spanUser').html(userName);

               
                // Add All Users
                for (i = 0; i < allUsers.length; i++) {
                    
                    AddUser(chatHub, allUsers[i].ConnectionId, allUsers[i].UserName, allUsers[i].idCarrera);
                
                }

                // Add Existing Messages
                for (i = 0; i < messages.length; i++) {
                    AddMessage(messages[i].UserName, messages[i].Message);
                }
            }

            // On New User Connected
            chatHub.client.onNewUserConnected = function (id, name, idcarrera) {
                AddUser(chatHub, id, name, idcarrera);
                var filtro = $("#txtNickName").val();
                var filtro = filtro.split(' ');
                var filtro2 = name.split(' ');
                if (filtro[0] == filtro2[0]) {
                    var $toastContent = $('<span>El usuario ' + name + ' se conecto </span>');
                    Materialize.toast($toastContent, 5000);
                }
                
            }

            
            // On User Disconnected
            chatHub.client.onUserDisconnected = function (id, userName) {
                var filtro = $("#txtNickName").val();
                var filtro = filtro.split(' ');
                var filtro2= userName.split(' ');
                $('#p' + id).remove();

                var ctrId = 'private_' + id;
                $('#' + ctrId).remove();
                if (filtro[0] == filtro2[0] && $("#txtNickName").val() != userName) {
                    var $toastContent = $('<span>El usuario ' + userName + ' se desconecto </span>');
                    Materialize.toast($toastContent, 5000);
                } else {
                    console.log("se desconecto " + userName);
                }
                
              

            }

            chatHub.client.messageReceived = function (userName, message, idcarrera) {

                AddMessage(userName, message, idcarrera);
            }


            chatHub.client.sendPrivateMessage = function (windowId, fromUserName, message) {

                var ctrId = 'private_' + windowId;


                if ($('#' + ctrId).length == 0) {

                    createPrivateChatWindow(chatHub, windowId, ctrId, fromUserName);

                }
                //Recibe chat.
                //Si entra al IF signiica que es del usuario que mando, si no es el usuario que recive.
                if (fromUserName == $('#txtNickName').val()) {
                    $('#' + ctrId).find('#divMessage').append('<div class="media-body"><div class="bubble bubble--alt" style=" text-align: right;">' + message + '</div></div>');
                } else {
                    //setInterval(blink, 200);
                    $('#' + ctrId).find('#divMessage').append('<div class="media-body"><div class="bubble" style=" text-align: left;">' + message + '</div>');
                    $(document).attr('title', fromUserName + " te ha escrito");
                    $('#' + ctrId).find('.header').removeClass("read").addClass("unread");
                    audioElement.play();
                }
               
               
                function blink() {
                    $('#' + ctrId).find('.header').fadeTo(100, 0.1).fadeTo(200, 1.0);
                }
                
          
              
                
               
                // set scrollbar
                var height = $('#' + ctrId).find('#divMessage')[0].scrollHeight;
                $('#' + ctrId).find('#divMessage').scrollTop(height);

            }

        }
        function AddUser(chatHub, id, name, idCarrera) {

            var userId = $('#hdId').val();
           
            var code = "";
            var filtro = $("#txtNickName").val();
            var filtro = filtro.split(' ');
            if (idCarrera == filtro[0]) {
                if (userId == id) {

                    code = $('<div">' + name + "</div>");

                }
                else {

                    code = $('<p id="p'+id+'"><a id="' + id + '" class="user" >' + name + '<a></p>');

                    $(code).click(function () {

                        var id = $(this).children('a').attr('id');

                        if (userId != id) {
                            OpenPrivateChatWindow(chatHub, id, name);
                            var ctrId = 'private_' + id;
                            $('#' + ctrId).find('#txtPrivateMessage').focus();
                        }
                           
                    });
                }

            }
           
            if ($('#p'+id).length > 0) {
                console.log('Ya existe');
            } else {
               
                $("#divusers").append(code);
            }
            
            
        }

        function AddMessage(userName, message, idcarrera) {

            var filtro = $("#txtNickName").val();
            var filtro = filtro.split(' ');
            if (filtro[0] == idcarrera) {
                $('#divChatWindow').append('<div class="media-body"> <div class="media"><div class="media-body">' + message + '<br/> <small class="text-muted">' + userName + '</small></div></div></div><br/>');

                var height = $('#divChatWindow')[0].scrollHeight;
                $('#divChatWindow').scrollTop(height);
            }
            
        }

        function OpenPrivateChatWindow(chatHub, id, userName) {

            var ctrId = 'private_' + id;

            if ($('#' + ctrId).length > 0) return;

            createPrivateChatWindow(chatHub, id, ctrId, userName);
          
            $('#' + ctrId).find('#txtPrivateMessage').focus();

        }
        
        function createPrivateChatWindow(chatHub, userId, ctrId, userName) {
           
            var div = '<div id="' + ctrId + '" class="ui-widget-content draggable white resizable" rel="0">' +
                       '<div class="header">' +
                              '<div  style="float:right;">' +
                              '<img id="imgDelete"  style="cursor:pointer;" src="/Img/ic_highlight_off_black_24dp_1x.png"/>' +
                           '</div>' +
                           '<i class="material-icons">account_circle</i>'+
                           '<span class="selText" rel="0">' + userName + '</span>' +
                       '</div>' +
                       '<div  id="divMessage" class="panel-body" style="height: 250px; overflow-y: scroll;">' +
                      
                       '</div>' +
                       '<div class="buttonBar">' +
                          '<input id="txtPrivateMessage" class="msgText" placeholder="Escribe un texto aquí"  type="text" />' +
                          '<input id="btnSendMessage" class="btn orange white-text waves-effect waves-light" type="button" value="Enviar"   />' +
                      '</div>' +
                    '</div>';

            var $div = $(div);

            $div.find('.header').click(function () {
                readd();
            });
            // DELETE BUTTON IMAGE
            $div.find('#imgDelete').click(function () {
                $('#' + ctrId).remove();
            });
            $(function () {

                $div.find('#imgMini').click(function () {
                    $('#' + ctrId).accordion({
                        collapsible: true
                    });
                });

            });

            
           
            function readd() {
                //setTimeout($('#'+ctrId).find('.header').stop(true,true).css("opacity", 1), 10);
                $('#' + ctrId).find('.header').removeClass("unread").addClass("read");
                $(document).attr('title', "Chat");
            };
            // Send Button event
            $div.find("#btnSendMessage").click(function () {
                
                $textBox = $div.find("#txtPrivateMessage");
                var msg = $textBox.val();
                if (msg.length > 0 && !(/^\s+$/.test(msg))) {
                    
                    chatHub.server.sendPrivateMessage(userId, msg);
                    $('#' + ctrId).find('.header').removeClass("unread").addClass("read");
                    $textBox.val('').focus();
                }
            });

            // Text Box event
            $div.find("#txtPrivateMessage").keypress(function (e) {
                if (e.which == 13) {
                    $div.find("#btnSendMessage").click();
                   
                }
            });

            $div.find("#txtPrivateMessage").click(function () {
                readd();
            });

            AddDivToContainer($div);

        }
     
        function AddDivToContainer($div) {
            $('#divContainer').prepend($div);

            $div.draggable({

                handle: ".header",
                stop: function () {

                }
            });

            //$div.resizable({

            //    stop: function () {

            //    }
            //});

        }

    </script>
</head>
<body>
    <form id="form1" runat="server">
     <div id="header">
        Chat
         <div class="right">
             <a href="Login.aspx" class="black-text"><i class="material-icons black-text">exit_to_app</i> Salir</a>
         </div>
    </div>
    <div id="divContainer" class="container row center center-aling">
        <br /><br />
        <div id="divLogin" class="login col s8 m8 l6 offset-m2 offset-s2 offset-l3 center center-aling">
            <div>
                Tu nombre:<br />
            <input disabled id="txtNickName" type="text" class="textBox" />
            </div>
            <div id="divButton" class="center center-align">
                <input id="btnStartChat" type="button" class="btn orange waves-effect waves-light" value="Iniciar Chat" />
                <br /><br />
            </div>
        </div>
        <div id="divChat" class="row " style="padding-top:40px;">
            <h3><SPAN ID="nameCarrera">Sala de chat</SPAN> </h3>
            <br />
            <br />
            <div class="col s12 m12 l7 chatRoom striped">
            <div class="panel panel-info">
                <div class="panel-heading orange darken-2">Chat de Todos  Bienvenido [<span id='spanUser'></span>]</div>
                <div class="panel-body">
                    <ul id="divChatWindow" class="media-list left-align" style="height: 500px;
	                overflow-y: scroll;" >
                    
                    </ul>
                </div>
                <div class="panel-footer">
                    <br />
                    <div class="input-group">
                        <input id="txtMessage" class="form-control" type="text" placeholder="Ingrese mensaje" />
                        <br /><span class="input-group-btn">                           
                            <button id="btnSendMsg" class="btn orange darken-1 waves-effect waves-light" type="button">Enviar</button>
                        </span><br /><br />
                    </div>
                </div>

            </div>
            <input id="hdId" type="hidden" />
            <input id="hdUserName" type="hidden" />
        </div>
        <div class="col s12 l5 m12">
            <div class="hide-on-large-only"><br /><br /></div>
            <div class="panel panel-primary">
                <div class="panel-heading" style="background-color:darkorange"> Usuarios Online</div>
                <div id="divusers" class="panel-body  orange lighten-4" style="cursor: pointer;display: block;height: 200px;overflow-y: scroll;">         
            </div>
            </div>
        </div>
        </div>   
    </div>
    </form>
</body>
</html>
